// SPDX-License-Identifier: Apache-2.0

#ifndef _BOOTLOADER_PRODUCT_H_
#define _BOOTLOADER_PRODUCT_H_

#include <platform_config.h>
#include <stdint.h>

#define BB02_STAGE1_PRODUCT_ID_BITBOX_MULTI (1u)
#define BB02_STAGE1_PRODUCT_ID_BITBOX_BTCONLY (2u)
#define BB02_STAGE1_PRODUCT_ID_BITBOX_PLUS_MULTI (3u)
#define BB02_STAGE1_PRODUCT_ID_BITBOX_PLUS_BTCONLY (4u)

#if defined(BB02_STAGE1_TARGET_PRODUCT_ID)
    #if BB02_STAGE1_TARGET_PRODUCT_ID != BB02_STAGE1_PRODUCT_ID_BITBOX_MULTI &&      \
        BB02_STAGE1_TARGET_PRODUCT_ID != BB02_STAGE1_PRODUCT_ID_BITBOX_BTCONLY &&    \
        BB02_STAGE1_TARGET_PRODUCT_ID != BB02_STAGE1_PRODUCT_ID_BITBOX_PLUS_MULTI && \
        BB02_STAGE1_TARGET_PRODUCT_ID != BB02_STAGE1_PRODUCT_ID_BITBOX_PLUS_BTCONLY
        #error "invalid bootloader target product"
    #endif
    #define BB02_STAGE1_PRODUCT_ID BB02_STAGE1_TARGET_PRODUCT_ID
#elif PRODUCT_BITBOX_MULTI == 1
    #define BB02_STAGE1_PRODUCT_ID BB02_STAGE1_PRODUCT_ID_BITBOX_MULTI
#elif PRODUCT_BITBOX_BTCONLY == 1
    #define BB02_STAGE1_PRODUCT_ID BB02_STAGE1_PRODUCT_ID_BITBOX_BTCONLY
#elif PRODUCT_BITBOX_PLUS_MULTI == 1
    #define BB02_STAGE1_PRODUCT_ID BB02_STAGE1_PRODUCT_ID_BITBOX_PLUS_MULTI
#elif PRODUCT_BITBOX_PLUS_BTCONLY == 1
    #define BB02_STAGE1_PRODUCT_ID BB02_STAGE1_PRODUCT_ID_BITBOX_PLUS_BTCONLY
#else
    #error "unknown product"
#endif

_Static_assert(BB02_STAGE1_PRODUCT_ID <= UINT16_MAX, "stage1 product id too large");

#endif
