// SPDX-License-Identifier: Apache-2.0

use alloc::{boxed::Box, vec::Vec};

use super::memory::PasswordStretchAlgo;

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum Model {
    Atecc608A,
    Atecc608B,
    OptigaTrustM3,
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum Error {
    SecureChip(SecureChipError),
    Status(i32),
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(i32)]
// Keep in sync with securechip.h's securechip_error_t.
pub enum SecureChipError {
    // Errors common to any securechip implementation
    Ifs = -1,
    InvalidArgs = -2,
    ConfigMismatch = -3,
    Salt = -4,
    // Currently only used by Optiga, but it is in the common errors so that the API of the
    // securechip is consistent and the caller does not need to distinguish between the chips at
    // the callsite.
    IncorrectPassword = -6,
    // The password stretch algo is not supported
    InvalidPasswordStretchAlgo = -7,
    Memory = -8,
    // Errors specific to the ATECC
    AteccZoneUnlockedConfig = -100,
    AteccZoneUnlockedData = -101,
    AteccSlotUnlockedIo = -103,
    AteccSlotUnlockedAuth = -104,
    AteccSlotUnlockedEnc = -105,
    AteccResetKeys = -106,
    // Errors specific to the Optiga
    OptigaCreate = -201,
    OptigaUnexpectedMetadata = -204,
    OptigaPal = -205,
    OptigaUnexpectedLen = -206,
}

pub trait SecureChip {
    /// Returns 32 bytes of randomness generated by the secure chip.
    fn random(&mut self) -> Result<Box<zeroize::Zeroizing<[u8; 32]>>, Error>;

    /// Prepares the secure chip for a new password and returns the stretched password.
    ///
    /// This reinitializes the secure-chip state used for password derivation and returns the same
    /// 32-byte value as [`stretch_password`] for the same `password` and
    /// `password_stretch_algo`, but may require fewer secure-chip operations.
    fn init_new_password(
        &mut self,
        password: &str,
        password_stretch_algo: PasswordStretchAlgo,
    ) -> Result<zeroize::Zeroizing<Vec<u8>>, Error>;

    /// Stretches `password` using secrets stored in the secure chip.
    ///
    /// The returned value is always 32 bytes long. Calling this function increments the relevant
    /// secure-chip monotonic counter.
    fn stretch_password(
        &mut self,
        password: &str,
        password_stretch_algo: PasswordStretchAlgo,
    ) -> Result<zeroize::Zeroizing<Vec<u8>>, Error>;

    /// Runs the secure-chip KDF with `msg` and returns the zeroizing 32-byte result.
    ///
    /// This must not increment a monotonic counter.
    ///
    /// `msg` must be at most 127 bytes long.
    fn kdf(&mut self, msg: &[u8]) -> Result<zeroize::Zeroizing<Vec<u8>>, Error>;

    /// Signs a 32-byte attestation challenge and writes the raw 64-byte P-256 signature to
    /// `signature`.
    fn attestation_sign(
        &mut self,
        challenge: &[u8; 32],
        signature: &mut [u8; 64],
    ) -> Result<(), ()>;

    /// Returns the remaining number of secure-chip monotonic counter increments.
    fn monotonic_increments_remaining(&mut self) -> Result<u32, ()>;

    /// Returns the detected secure-chip model.
    fn model(&mut self) -> Result<Model, ()>;

    /// Resets the secure-chip objects involved in password stretching.
    fn reset_keys(&mut self) -> Result<(), ()>;

    #[cfg(feature = "app-u2f")]
    /// Sets the U2F counter to `counter`.
    ///
    /// This is intended for initialization only.
    fn u2f_counter_set(&mut self, counter: u32) -> Result<(), ()>;
}
