# SPDX-License-Identifier: Apache-2.0

language = "C"

include_guard = "BITBOX02_RUST_H"

include_version = true

header = '''
#include "platform/platform_config.h"
#include "securechip/securechip.h"
#include "util.h"
#include <ui/components/confirm.h>
'''

[parse]
# Parse dependencies for types ...
parse_deps = true

# ... but only parse these crates.
include = ["bitbox02", "bitbox02-rust", "bitbox-securechip", "util", "bitbox-aes", "bitbox-da14531", "bitbox-framed-serial-link", "bitbox-bytequeue", "bitbox-usb-report-queue"]

# also generate bindings from these crates.
extra_bindings = ["bitbox02", "bitbox02-rust", "bitbox-securechip", "util", "bitbox-aes", "bitbox-da14531", "bitbox-framed-serial-link", "bitbox-bytequeue", "bitbox-usb-report-queue"]

[export]
# malloc, free declared in bitbox02-rust-c/src/c_alloc.rs, but does not need to be exported, as it
# already exists in stdlib.h.
exclude = [
  "malloc",
  "free",
  "Abort",
]
