language = "C"

include_guard = "BITBOXBASE_RUST_H"

include_version = true

includes = ["commander/commander.h", "bitboxbase.pb.h"]

[parse]
# Parse dependencies for types ...
parse_deps = true

# ... but only parse this crate.
include = ["bitbox02-rust", "util-c"]

# also generate bindings from these crates.
extra_bindings = ["util-c"]

[export]
# malloc, free declared in bitbox02-rust-c/src/alloc.rs, but does not need to be exported, as it
# already exists in stdlib.h.
exclude = ["malloc", "free"]
