#!/usr/bin/env bash

set -e

# Import all keys
find ./releases/pubkeys -name '*.asc' -exec gpg --import {} \;

# Verify all sigs.
find ./releases -name '*.sig' |
    while read file; do
        echo "checking $file"
        gpg --verify $file $(dirname $file)/assertion.txt
    done
