#!/bin/bash

set -e

# Check style

./.ci/check-style
make -C py
./.ci/check-pep8

# Bootloader variants
make -j8 bootloader
make -j8 bootloader-devdevice
make -j8 bootloader-production

# Firmware
make -j8 firmware

make -j8 factory-setup

# Build and run Unit tests
make -j8 unit-test
make -j8 run-unit-tests
# Check that coverage report building is working.
make coverage

make -C tools/go/src/atecc608a test

# Build device tests
# make -j8 device-test

# ./scripts/tidy # run tidy on the firmware build
