#!/bin/bash

set -e

# Deny warnings in rust. CI will fail to compile any code with warnings in it.
export RUSTFLAGS="-Dwarnings"

# Check style

./.ci/check-style
make -C py
./.ci/check-pep8

# check ./releases sigs
./.ci/check-release-sigs

# Make build directories so we can do some static analysis
make prepare-tidy
./.ci/check-tidy

# Build and run Unit tests
make -j8 unit-test
make -j8 run-unit-tests
# Check that coverage report building is working.
make coverage

# Bootloader variants
make -j8 bootloader
make -j8 bootloader-devdevice
make -j8 bootloader-devdevice-locked
make -j8 bootloader-production

make -j8 bootloader-btc
make -j8 bootloader-btc-devdevice
make -j8 bootloader-btc-production

make -j8 bootloader-bitboxbase
make -j8 bootloader-bitboxbase-devdevice
make -j8 bootloader-bitboxbase-production

# Firmware
make -j8 firmware
make -j8 firmware-semihosting
make -j8 firmware-btc
make -j8 firmware-bitboxbase
make -j8 factory-setup

make -C tools/go/src/atecc608a test

# Build device tests
make -j8 device-tests

# Don't generate graphics in CI
(cd build; cmake -DDOC_GRAPHS=NO ..)
make -j8 docs
