#!/usr/bin/env python3

import json
import subprocess
import sys

commits = subprocess.check_output(["git", "rev-list", "--reverse", sys.argv[1]], text=True).split()

if commits:
    total = len(commits)
    matrix = [
        {"commit": commit, "height": height, "total": total}
        for height, commit in enumerate(commits, start=1)
    ]
    print(json.dumps({"include": matrix}))
