#!/bin/bash
#
# This script works on merge commits. <rev>^1 means the first parent of <rev>.
#
#     -o--o--o <-- HEAD^1 (e.g., master)
#       \     \
#        \     o <-- HEAD (checked out by github action on pull request event)
#         \   /
#          o-o <-- HEAD^2 (e.g. feature branch)

set -e

if git diff --name-only HEAD^1 HEAD | grep -E '^(\.containerversion|Dockerfile)' >/dev/null; then
	echo "modified=true"
	exit
fi
echo "modified=false"
