#!/bin/bash
# Copyright 2019 Shift Cryptosecurity AG
# Copyright 2020-2024 Shift Crypto AG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The script runs all CI builds and checks in a Docker container.
# It accepts two positional arguments:
# 1. A workspace dir, the root of the git repo clone, to be mounted in the container.
# 2. A git revision (see man gitrevisions) to compare against HEAD to filter out modified and new
#    files. Some scripts only run on that subset.

set -e
set -x

CONTAINER_REPO=shiftcrypto/firmware_v2
CONTAINER_VERSION=$(cat .containerversion)
CONTAINER=$CONTAINER_REPO:${CONTAINER_VERSION}

WORKSPACE_DIR="$1"
if [ -z "${WORKSPACE_DIR}" ]; then
  echo "Workspace dir path is empty."
  exit 1
fi

TARGET_BRANCH="$2"
# The safe.directory config is so that git commands work. even though the repo folder mounted in
# Docker is owned by root, which can be different from the owner on the host.
docker run -e TARGET_BRANCH="${TARGET_BRANCH}" \
	--cap-add SYS_PTRACE \
	--volume ${WORKSPACE_DIR}:/bitbox02-firmware/ \
	--workdir /bitbox02-firmware \
	${CONTAINER} \
	bash -c "git config --global --add safe.directory /bitbox02-firmware && ./.ci/ci"
