#!/bin/bash -e

# Fetch origin/master so that we can diff when checking coding style.
git remote set-branches --add origin master
git fetch

docker run -v ${TRAVIS_BUILD_DIR}:/bitbox02-firmware/ \
       -i shiftcrypto/firmware_v2:1 \
       bash -c "make -C /bitbox02-firmware ci"
