include = [{ path = "../../../.cargo/config.local.toml", optional = true }]

[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/probe-rs/rtt-target.git?rev=08309db569ff5b93e9e77165984e32ebb22de277"]
git = "https://github.com/probe-rs/rtt-target.git"
rev = "08309db569ff5b93e9e77165984e32ebb22de277"
replace-with = "vendored-sources"

[source."git+https://github.com/BitBoxSwiss/rust-bip32-ed25519?tag=v0.2.1"]
git = "https://github.com/BitBoxSwiss/rust-bip32-ed25519"
tag = "v0.2.1"
replace-with = "vendored-sources"

[source."git+https://github.com/BitBoxSwiss/rust-bip39.git?branch=bitbox-20250922"]
git = "https://github.com/BitBoxSwiss/rust-bip39.git"
branch = "bitbox-20250922"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "../../external/vendor"

[alias]
bitbox03-boot0-stm32u5a9j-dk = "build -p bitbox03-boot0 --target=thumbv8m.main-none-eabihf --features board-stm32u5a9j-dk,rtt"
bitbox03-boot0-stm32u5a9j-dk-release = "build -p bitbox03-boot0 --target=thumbv8m.main-none-eabihf --release --features board-stm32u5a9j-dk"
bitbox03-boot1-stm32u5a9j-dk = "build -p bitbox03-boot1 --target=thumbv8m.main-none-eabihf --features board-stm32u5a9j-dk,rtt"
bitbox03-boot1-stm32u5a9j-dk-release = "build -p bitbox03-boot1 --target=thumbv8m.main-none-eabihf --release --features board-stm32u5a9j-dk"
