#!/usr/bin/env bash

# Format all files in repository that we should be formatting

# Exit on error
set -e

# Exit on pipe fail
set -o pipefail

CLANGFORMAT=${CLANGFORMAT:-clang-format-21}
CLANGFORMAT_FLAGS=${CLANGFORMAT_FLAGS:--i}
VERBOSE=${VERBOSE:-NO}

command -v ${CLANGFORMAT} >/dev/null 2>&1 || { echo >&2 "${CLANGFORMAT} is missing"; exit 1; }

# TODO: Put all external code in "external"
FILES=$(git ls-files src test | \
	grep -E '\.(c|h)$' | \
	grep -v -E '^src/ui/fonts/' | \
	grep -v -E '^src/rust/bitbox-secp256k1/depend/' | \
	grep -v -E '^src/rust/fatfs-sys/depend/' | \
	grep -v -E '/ugui')

if [ "${VERBOSE}" != "NO" ] ; then
	echo ${FILES}
fi

${CLANGFORMAT} ${CLANGFORMAT_FLAGS} ${FILES}
