#!/usr/bin/env python3
"""Compatibility wrapper for the shared version helper."""

import sys

from generate_version_headers import main_get_version


if __name__ == "__main__":
    sys.exit(main_get_version())
