// SPDX-License-Identifier: Apache-2.0

#![no_std]

extern crate alloc;

use alloc::string::String;

struct Group {
    count: u16,
    decimals: u8,
    unit_len: u8,
    unit_is_ambiguous: bool,
}

pub struct Params {
    pub unit: String,
    pub contract_address: [u8; 20],
    pub decimals: u8,
    unit_is_ambiguous: bool,
}

impl Params {
    /// Whether multiple registered contracts share this displayed unit, regardless of decimals.
    pub fn unit_is_ambiguous(&self) -> bool {
        self.unit_is_ambiguous
    }
}

// Includes `const ALL: &[Group] = ...` listing all params by decimals, unit length and ambiguity.
// This way we don't repeat the decimal in every token, saving ~1 byte of binary space per token.
// Each group's ASCII units are concatenated in contract-address order, saving a pointer per token.
// Addresses and units are concatenated across groups, whose counts determine the lookup offsets.
// Grouping by ambiguity avoids a separate symbol index for contract-identity confirmation.
// Generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/tokens.rs"));

fn decode_unit(data: &[u8], alphabet: &[u8], start: usize, len: usize) -> String {
    let mut unit = String::with_capacity(len);
    // Six-bit alphabet indices are packed least-significant bits first, without padding per unit.
    for index in start..start + len {
        let bit_offset = index * 6;
        let shift = bit_offset % 8;
        let mut code = data[bit_offset / 8] >> shift;
        if shift > 2 {
            code |= data[bit_offset / 8 + 1] << (8 - shift);
        }
        unit.push(char::from(alphabet[usize::from(code & 0x3f)]));
    }
    unit
}

pub fn get(chain_id: u64, contract_address: [u8; 20]) -> Option<Params> {
    if chain_id != 1 {
        return None;
    }
    let mut address_offset = 0;
    let mut unit_offset = 0;
    for group in ALL {
        let count = usize::from(group.count);
        let unit_len = usize::from(group.unit_len);
        let address_end = address_offset + count;
        if let Ok(index) =
            CONTRACT_ADDRESSES[address_offset..address_end].binary_search(&contract_address)
        {
            let start = unit_offset + index * unit_len;
            return Some(Params {
                unit: decode_unit(UNITS, UNIT_ALPHABET, start, unit_len),
                contract_address,
                decimals: group.decimals,
                unit_is_ambiguous: group.unit_is_ambiguous,
            });
        }
        address_offset = address_end;
        unit_offset += count * unit_len;
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use hex_lit::hex;

    extern crate std;
    use std::fs::File;
    use std::io::{self, BufRead};
    use std::vec::Vec;

    const ALPHABET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

    #[test]
    fn test_decode_unit() {
        let data = hex!("40a6cd74efff");
        let expected = "AZaz09+/";
        assert_eq!(decode_unit(&data, ALPHABET, 0, expected.len()), expected);
        for index in 0..expected.len() {
            assert_eq!(
                decode_unit(&data, ALPHABET, index, 1),
                &expected[index..index + 1],
            );
        }
        assert_eq!(decode_unit(&data, ALPHABET, 2, 4), "az09");
    }

    #[test]
    fn test_decode_unit_tail() {
        assert_eq!(decode_unit(&[], ALPHABET, 0, 0), "");
        assert_eq!(decode_unit(&hex!("19"), ALPHABET, 0, 1), "Z");
        assert_eq!(decode_unit(&hex!("4000"), ALPHABET, 1, 1), "B");
        assert_eq!(decode_unit(&hex!("402000"), ALPHABET, 2, 1), "C");
        assert_eq!(decode_unit(&hex!("40200c"), ALPHABET, 3, 1), "D");
    }

    #[test]
    fn test_get() {
        // Not found for chainID 0.
        assert!(get(
            0,
            *b"\x0f\x72\x71\x4b\x35\xa3\x66\x28\x5d\xf8\x58\x86\xa2\xee\x17\x46\x01\x29\x2a\x17"
        )
        .is_none());

        // Contract address doesn't exist on chainID 1.
        assert!(get(
            1,
            *b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x17"
        )
        .is_none());

        let params = get(
            1,
            *b"\x00\x00\x00\x00\x00\x08\x5d\x47\x80\xb7\x31\x19\xb6\x44\xae\x5e\xcd\x22\xb3\x76",
        )
        .unwrap();
        assert_eq!(params.unit, "TUSD");
        assert_eq!(
            params.contract_address,
            *b"\x00\x00\x00\x00\x00\x08\x5d\x47\x80\xb7\x31\x19\xb6\x44\xae\x5e\xcd\x22\xb3\x76"
        );
        assert_eq!(params.decimals, 18);

        let params = get(
            1,
            *b"\xbf\x05\x57\x19\x88\xda\xab\x22\xd3\x3c\x28\xbb\xb1\x35\x66\xea\xe9\xde\xe6\x26",
        )
        .unwrap();
        assert_eq!(params.unit, "999");
        assert_eq!(params.decimals, 3);
    }

    #[test]
    fn test_get_all() {
        let file = File::open("src/tokens.txt").unwrap();
        let reader = io::BufReader::new(file);
        let lines: Vec<_> = reader
            .lines()
            .map(Result::unwrap)
            .filter(|line| !line.starts_with('#'))
            .collect();
        let tokens: Vec<Vec<&str>> = lines.iter().map(|line| line.split(';').collect()).collect();

        for parts in &tokens {
            let expected_unit = parts[0];
            let contract_address: [u8; 20] = hex::decode(parts[1].strip_prefix("0x").unwrap())
                .unwrap()
                .try_into()
                .unwrap();
            let expected_decimals: u8 = parts[2].parse().unwrap();

            let params = get(1, contract_address).unwrap();
            assert_eq!(params.contract_address, contract_address,);
            assert_eq!(params.unit, expected_unit);
            assert_eq!(params.decimals, expected_decimals);
            // Check all registry entries, including same-symbol/different-decimal pairs.
            assert_eq!(
                params.unit_is_ambiguous(),
                tokens
                    .iter()
                    .any(|other| other[0] == expected_unit && other[1] != parts[1]),
                "{} ({})",
                expected_unit,
                parts[1],
            );
        }
    }
}
