// SPDX-License-Identifier: Apache-2.0

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const FNV1A64_OFFSET: u64 = 0xcbf29ce484222325;
const FNV1A64_PRIME: u64 = 0x100000001b3;

fn main() {
    let locales_dir = locales_dir();
    let en_path = locales_dir.join("en/firmware.json");
    let de_path = locales_dir.join("de/firmware.json");

    println!("cargo::rerun-if-changed={}", en_path.display());
    println!("cargo::rerun-if-changed={}", de_path.display());

    let english = read_flattened_json(&en_path);
    let german = read_flattened_json(&de_path);
    let german_entries = locale_entries(&english, &german, &de_path);

    let mut generated = generated_table(&german_entries);
    generated.push_str(&generated_valid_en_hashes(&english));

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set")).join("i18n.rs");
    fs::write(out, generated).expect("failed to write generated i18n table");
}

fn locales_dir() -> PathBuf {
    Path::new(&env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"))
        .join("../../i18n/locales")
}

fn read_flattened_json(path: &Path) -> BTreeMap<String, String> {
    let data = fs::read_to_string(path)
        .unwrap_or_else(|err| panic!("failed to read locale file {}: {err}", path.display()));
    let value: serde_json::Value = serde_json::from_str(&data)
        .unwrap_or_else(|err| panic!("failed to parse locale file {}: {err}", path.display()));

    let mut flattened = BTreeMap::new();
    flatten_json("", &value, &mut flattened, path);
    flattened
}

fn flatten_json(
    prefix: &str,
    value: &serde_json::Value,
    out: &mut BTreeMap<String, String>,
    path: &Path,
) {
    match value {
        serde_json::Value::Object(map) => {
            for (key, value) in map {
                let key = if prefix.is_empty() {
                    key.to_owned()
                } else {
                    format!("{prefix}.{key}")
                };
                flatten_json(&key, value, out, path);
            }
        }
        serde_json::Value::String(value) => {
            out.insert(prefix.to_owned(), value.to_owned());
        }
        _ => panic!(
            "locale file {} contains a non-string leaf at key '{}'",
            path.display(),
            prefix
        ),
    }
}

fn locale_entries(
    english: &BTreeMap<String, String>,
    locale: &BTreeMap<String, String>,
    locale_path: &Path,
) -> Vec<(String, String)> {
    let mut by_english = BTreeMap::<String, String>::new();
    for key in locale.keys() {
        if !english.contains_key(key) {
            panic!(
                "locale file {} contains key '{}' which does not exist in English",
                locale_path.display(),
                key
            );
        }
    }
    for (key, english) in english {
        let translated = locale.get(key).unwrap_or_else(|| {
            panic!(
                "locale file {} is missing English key '{}'",
                locale_path.display(),
                key
            )
        });
        if placeholder_count(english) != placeholder_count(translated) {
            panic!(
                "placeholder mismatch in {} at key '{}': {:?} vs {:?}",
                locale_path.display(),
                key,
                english,
                translated
            );
        }
        match by_english.get(english) {
            Some(existing) if existing != translated => {
                panic!(
                    "locale file {} has conflicting translations for {:?}: {:?} and {:?}",
                    locale_path.display(),
                    english,
                    existing,
                    translated
                );
            }
            Some(_) => {}
            None => {
                by_english.insert(english.to_owned(), translated.to_owned());
            }
        }
    }
    by_english.into_iter().collect()
}

fn placeholder_count(value: &str) -> usize {
    let mut count = 0;
    let mut rest = value;
    while let Some((start, len)) = next_placeholder(rest) {
        count += 1;
        rest = &rest[start + len..];
    }
    count
}

fn next_placeholder(value: &str) -> Option<(usize, usize)> {
    match (value.find("{}"), value.find("{:?}")) {
        (Some(a), Some(b)) if a <= b => Some((a, 2)),
        (Some(_), Some(b)) => Some((b, 4)),
        (Some(a), None) => Some((a, 2)),
        (None, Some(b)) => Some((b, 4)),
        (None, None) => None,
    }
}

fn generated_table(entries: &[(String, String)]) -> String {
    let mut out = String::from("// @generated by build.rs\n\n");
    out.push_str("pub(crate) const DE_TRANSLATIONS: &[(u64, &str)] = &[\n");
    let mut by_key = BTreeMap::<u64, &str>::new();
    for (english, translated) in entries {
        let key = translation_key(english);
        if let Some(existing) = by_key.insert(key, english) {
            panic!("translation key collision between {existing:?} and {english:?}");
        }
        out.push_str("    (");
        out.push_str(&format!("0x{key:016x}"));
        out.push_str(", ");
        out.push_str(&format!("{translated:?}"));
        out.push_str("),\n");
    }
    out.push_str("];\n");
    out
}

fn generated_valid_en_hashes(english: &BTreeMap<String, String>) -> String {
    let mut hashes: Vec<u64> = english
        .values()
        .map(|value| translation_key(value))
        .collect();
    hashes.sort_unstable();
    hashes.dedup();

    let mut out = String::from("\npub(crate) const VALID_EN_HASHES: &[u64] = &[\n");
    for hash in hashes {
        out.push_str(&format!("    0x{hash:016x},\n"));
    }
    out.push_str("];\n");
    out
}

fn translation_key(value: &str) -> u64 {
    let mut hash = FNV1A64_OFFSET;
    for byte in value.as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(FNV1A64_PRIME);
    }
    hash
}
