# SPDX-License-Identifier: Apache-2.0

[package]
name = "bitbox-mcu-stm32u5"
version = "0.1.0"
edition = "2024"
authors = ["Shift Crypto AG <support@bitbox.swiss>"]
description = "Selected STM32U5 PAC for bitbox02-firmware"
license = "Apache-2.0"

[lib]
test = false
doctest = false

[features]
stm32u5a9 = ["stm32-metapac/stm32u5a9nj"]
stm32u5g9 = ["stm32-metapac/stm32u5g9zj"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))'.dependencies]
stm32-metapac = { version = "21.0.0", features = ["rt"] }
